# Generated by Django 4.2.1 on 2023-05-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_reply_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Board',
        ),
    ]
