# Generated by Django 4.2.1 on 2023-05-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_replytrainer_replyuser_delete_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_key', models.CharField(max_length=12)),
            ],
        ),
    ]
