# Generated by Django 4.2.1 on 2023-06-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(default='', max_length=40, upload_to='media/'),
        ),
    ]
