# Generated by Django 4.2.1 on 2023-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_board_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(default='', max_length=40, null=True, upload_to='mysite/media/'),
        ),
    ]
