# Generated by Django 4.2.1 on 2023-06-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_board_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replytrainer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='replytrainer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='replytrainer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='replyuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='replyuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='replyuser',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='replytrainer',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mysite.board'),
        ),
        migrations.AddField(
            model_name='replyuser',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mysite.board'),
        ),
    ]
