# Generated by Django 4.2.1 on 2023-06-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_remove_replytrainer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytrainer',
            name='board',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.board'),
        ),
    ]
