# Generated by Django 4.2.1 on 2023-06-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_alter_replytrainer_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.board')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'comment',
            },
        ),
        migrations.RemoveField(
            model_name='replyuser',
            name='board',
        ),
        migrations.RemoveField(
            model_name='replyuser',
            name='writer',
        ),
        migrations.DeleteModel(
            name='ReplyTrainer',
        ),
        migrations.DeleteModel(
            name='ReplyUser',
        ),
    ]
