# Generated by Django 4.2.1 on 2023-06-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_comment_remove_replyuser_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentT', models.TextField()),
                ('created_atT', models.DateTimeField(auto_now_add=True)),
                ('authorT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.trainer')),
                ('postT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.board')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'commentT',
            },
        ),
    ]
