# Generated by Django 4.2.1 on 2023-06-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_commentt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentT',
        ),
    ]
